### ISSUE TITLE
add flag to string macro to specify size

### ISSUE THREAD

**Issue by simonbyrne** [mkitti/StaticStrings.jl#2]
[Julia non-standard literals support an extra "flag" argument](https://docs.julialang.org/en/v1/manual/metaprogramming/#meta-non-standard-string-literals): you could use this to specify the size, e.g.
```
N"Hello World!"16
```
would store the string in a tuple of length 16 (and use zero-padding for the rest)

**Comment by mkitti** [comment]
Can you figure out how to make this not allocate?

**Comment by simonbyrne** [comment]
I think
```julia
macro N_str(ex,N)
    quote
        NString{$N}(unescape_string($ex))
    end
end
```

**Comment by simonbyrne** [comment]
Or was there something else you had in mind?

**Comment by mkitti** [comment]
I believe this is now done.

```julia
julia> using StaticStrings

julia> Static"Thank you for using StaticStrings.jl"64
Static"Thank you for using StaticStrings.jl\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"64

julia> ans |> print
Thank you for using StaticStrings.jl

julia> @allocated Static"Thank you for using StaticStrings.jl"64
0

julia> ncodeunits(Static"Thank you for using StaticStrings.jl"64)
64

julia> ncodeunits(Short"Thank you for using StaticStrings.jl"64)
36
```

`ShortStaticString` and `LongStaticString` may need some additional thought though.
